name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, PNPM
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install PNPM and dependcies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build Electron app
        run: |
          pnpm run build
          pnpm run app:dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # yeah no way to tell which format is which
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-dist-${{ github.sha }}
          path: |
            dist/*.dmg
            dist/*.pkg
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.exe
            dist/*.msi
